name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Fix dependencies
        run: |
          sudo apt update
          sudo apt install -y libtinfo5 || true

      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: "3.10"
          buildozer-cmd: android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
